### ISSUE TITLE
Can not start this extension.

### ISSUE THREAD

**Issue by tronghuan** [cedcommerce/Magento2-Developer-Debug-Tool#1]
When I run command: bin/magento setup:upgrade  I see this error.
Autoload error: Invalid Document 
Element 'config', attribute 'xsi:noNamespaceSchemaLocation': The attribute 'xsi:noNamespaceSchemaLocation' is not allowed.
Line: 1

**Comment by thienphucvx** [comment]
https://github.com/thienphucvx/Magento2-Developer-Debug-Tool . Download it and install. It will work.

**Comment by cedcommerce** [comment]
This issue is resolved now.
