### ISSUE TITLE
Toolbar is slow.

### ISSUE THREAD

**Issue by Hexmage** [cedcommerce/Magento2-Developer-Debug-Tool#10]
On php7 the toolbar is being incredibly slow, unresponsive and using a lot of my CPU.
This makes me think there is a loop somewhere in the code.

**Comment by cedcommerce** [comment]
Hi Hexmage,
We checked this module on PHP7 environment everything is looking fine.
May be it is your system issue.

Kindly check your environment with fresh magento2 installation and place one order. 
Let me know if you are facing this issue only with our module.

Thank You

**Comment by Hexmage** [comment]
It was the first Module I had installed on a fresh Magento 2.1 environment with Sample Data.

I haven't had this issue with any other module I installed afterwards, but this one is still really slow when I re-enabled it.

**Comment by michabejan** [comment]
I have the same issue.

**Comment by guido7171** [comment]
I also experienced the slowness. It seems only to be a chrome issue. Firefox gives me a workable debug bar! Very nice!  PHP7.0.8 M2.1.2CE

**Comment by obuhovski** [comment]
I found a solution. You just need to remove these lines:
https://github.com/cedcommerce/Magento2-Developer-Debug-Tool/blob/master/view/frontend/web/css/devtool.css#L212-L213

**Comment by bnymn** [comment]
I have the same issue in my Chrome browser.
