### ISSUE TITLE
Exception "Strict Notice" when setup:di:compile after setup:upgrade

### ISSUE THREAD

**Issue by philippe-foisy** [cedcommerce/Magento2-Developer-Debug-Tool#11]
Hi folks

Im running Magento 2.1.2 with sample data

Downloaded the module, unzipped it and installed it into my project. All via the CLI. After upgrading, this error popped up while recompiling the dependency exceptions

[Exception] Strict Notice: Declaration of Ced\DevTool\Model\Framework\Event\Invoker\InvokerDefault::_callObserverMethod() should be compatible with Magento\Framework\Event\Invoker\InvokerDefault::_callObserverMethod($object, $observer) in /Users/Whatever/Projets/dev.testMagentoCE2x/app/code/Ced/DevTool/Model/Framework/Event/Invoker/InvokerDefault.php on line 11

This happened at this step of the compilation : 
Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% 1 sec 39.5 Mi
Proxies code generation... 1/7 [====>-----------------------]  14% 1 sec 43.8 Mi
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 43.8 MiB
BAM

Got any ideas ? Since i'm a humble rookie, dont hesitate to point me in the right direction. Thx !

**Comment by cedcommerce** [comment]
Thanks for reporting the issue.
Just delete Ced\DevTool\Model\Framework\Event\Invoker\InvokerDefault.php and your porblem will be resolved.
Let us know if you are facing any other issue.

**Comment by philippe-foisy** [comment]
Hello again folks

First, I edited the InvokerDefault.php file name by adding a "_" in the name. setup:di:compile returned me this error :
[Exception]
Strict Notice: Declaration of Ced\DevTool\Model\Framework\Event\Invoker\InvokerDefault::_callObserverMethod() should be compatible with Magento\Framework\Event\Invoker\InvokerDefault::_callObserverMethod($object, $observer) in /Users/pfoisy/Projets/dev.testMagentoCE2x/app/code/Ced/DevTool/Model/Framework/Event/Invoker/_InvokerDefault.php on line 11

Afterward, I just deleted the said file (but not the folder) and the CLI returned this error :
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 43.8 MiB
PHP Fatal error : Cannot use Magento\Framework\Event\Observer as Observer because the name is already in use in /Users/pfoisy/Projets/dev.testMagentoCE2x/app/code/Ced/DevTool/Model/Predispatch.php on line 6
Fatal error: Cannot use Magento\Framework\Event\Observer as Observer because the name is already in use in /Users/pfoisy/Projets/dev.testMagentoCE2x/app/code/Ced/DevTool/Model/Predispatch.php on line 6 

Any hints ?

**Comment by cedcommerce** [comment]
Kindly flush the cache, then try again. Let me know if still you are facing the same issue.
Are you using latest package?
If not then you can try latest one as these issues are already resolved in latest package.

**Comment by philippe-foisy** [comment]
Cleaned the cache (anyway, cache is disable since im on my own station). Flushed it anyway. Still the PHP Fatal error is returned.
I downloaded the package yesterday so I guess it's the latest ?
