### ISSUE TITLE
Composer installation does not work

### ISSUE THREAD

**Issue by younkim** [cedcommerce/Magento2-Developer-Debug-Tool#12]
I followed the composer commands in the `README` of this repo. However, it does not work and gives

    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - The requested package cedcommerce/magento2-developer-debug-tool could not be found in any version, there may be a typo in the package name.

I'm not sure if adding the Github repo to `composer.json` works for composer installation, does it? I've always used Packagist to server open source Github repo code.

**Comment by cedcommerce** [comment]
Package name is updated to Ced , Kindly use as below
composer require ced/magento2-developer-debug-tool:*
