### ISSUE TITLE
XML bug

### ISSUE THREAD

**Issue by PeterDab** [cedcommerce/Magento2-Developer-Debug-Tool#2]
After install of module, could not access backend.
the system message:
"There has been an error processing your request"
"String could not be parsed as XML"
Best Regards
Peter

**Comment by code-K** [comment]
:+1:  I have the exact same issue.. -.- any updates on this??

**Comment by mohd1677** [comment]
I have the same issue.

**Comment by cedcommerce** [comment]
This issue is resolved now.
