### ISSUE TITLE
Exception generated while installation

### ISSUE THREAD

**Issue by yogicse** [cedcommerce/Magento2-Developer-Debug-Tool#8]
[Exception]  
  Strict Notice: Declaration of Ced\DevTool\Model\Framework\Event\Invoker\InvokerDefault::_callObserverMethod() should be compatible with Magento\Framework\Event\Invoker\InvokerDefault::_callObserverMethod($object, $observer) in /Applications/XAMPP/xamppfiles/ht  
/app/code/Ced/DevTool/Model/Framework/Event/Invoker/InvokerDefault.php on line 26

**Comment by cedcommerce** [comment]
Issue resolved
